---
- hosts: all

  vars:
    - setupepel: "no"

  tasks:

    - name: setup epel 8
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        state: present
      when:
        - setupepel == "yes"

    - name: install google-authenticator and qrencode-libs
      yum:
        name:
          - google-authenticator
          - qrencode-libs
        state: present

    - name: setup pam.d to use OTP for sudo
      pamd:
        name: sudo
        type: auth
        control: include
        module_path: system-auth
        new_type: auth
        new_control: required
        new_module_path: pam_google_authenticator.so
        module_arguments: 'secret=${HOME}/.google_authenticator echo_verification_code'
        state: before

    - name: change /etc/motd
      copy:
        dest: /etc/motd
        content: |
          Um OTP Token für sudo zu nutzen, führen Sie bitte diesen Befehl aus:

          google-authenticator -t -d -f -r 3 -R 30 -w 3 -s ~/.google_authenticator

        owner: root
        mode: '0644'
